CREATE TABLE [dbo].[FILMBLOCKS]
(
	[FilmID] INT NOT NULL,
	[BlockID] INT NOT NULL,
	PRIMARY KEY (FilmID, BlockID),
	FOREIGN KEY (FilmID) REFERENCES FILMS(FilmID),
	FOREIGN KEY (BlockID) REFERENCES BLOCKS(BlockID)
)