CREATE TABLE [dbo].[FILMARTISTS]
(
	[FilmID] INT NOT NULL,
	[ArtistID] INT NOT NULL,
	PRIMARY KEY (FilmID, ArtistID),
	FOREIGN KEY (FilmID) REFERENCES FILMS(FilmID),
	FOREIGN KEY (ArtistID) REFERENCES ARTISTS(ArtistID)
)
