CREATE TABLE [dbo].[FILMARTIST]
(
	[FilmID] INT NOT NULL,
	[ArtistID] INT NOT NULL,
	PRIMARY KEY (FilmID, ArtistID),
	FOREIGN KEY (FilmID) REFERENCES FILM(FilmID),
	FOREIGN KEY (ArtistID) REFERENCES ARTIST(ArtistID)
)
